Skip tests affected by lack of implementation of _TorchScriptTesting:… (#3882)
…:queue_push for XPU device

Torch script is deprecated, therefore tests failing with
NotImplementedError: The operator '_TorchScriptTesting::queue_push' is
not currently implemented for the XPU device should be skipped.

Fixes: [#3477](https://github.com/intel/torch-xpu-ops/issues/3477)

---------

Co-authored-by: Adam Stachowicz <adam.stachowicz@intel.com>
Co-authored-by: Benedykt Bela <benedykt.bela@intel.com>