Fix SYCL_PRINT macro (#2053)
This PR makes the SYCL_PRINT macro usable on Windows. Without this
change the usage of the macro for debugging purposes on Windows causes
compilation errors:
```
error C3878: syntax error: unexpected token 'char' following 'declaration'
note: missing ',' or ';' after previous declaration?
note: the template instantiation context (the oldest one first) is
error C2065: 'fmt_var': undeclared identifier
error C2760: syntax error: ']' was unexpected here; expected 'expression'
error C3878: syntax error: unexpected token '=' following 'expression'
```