Remove xpu specific pin memory implementation (#3087)
# Motivation
Refer to
https://github.com/pytorch/pytorch/blob/1ef51a6dab3f9fbb0ef35dbeea4ab36c7832a594/aten/src/ATen/native/native_functions.yaml#L4708-L4729,
we can see that `pin_memory` and `is_pinned` are device-agnostic. So we
should remove XPU-specific implementation.

Without this PR, a gap currently exists:
```
import torch
a = torch.randn(100, device='xpu')
b = a.pin_memory() # this works well, but we expect it should fail.
```

With this PR, a RuntimeError would be raise regarding to
https://github.com/pytorch/pytorch/blob/1ef51a6dab3f9fbb0ef35dbeea4ab36c7832a594/aten/src/ATen/native/Memory.cpp#L59:
```
import torch
a = torch.randn(100, device='xpu')
b = a.pin_memory() # here raise a RuntimeError: only dense CPU tensors can be pinned
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cannot pin 'XPUFloatType' only dense CPU tensors can be pinned
```