addcmul | Early exit if inputs are on different devices (CPU and XPU) (#2985)
Fixes https://github.com/intel/torch-xpu-ops/issues/2515

This patch introduces early exit with user-friendly error message.
Without this TORCH_CHECK, the functionality doesn't work anyway, but the
error message is generic

```Python
RuntimeError: iter.device(arg).is_xpu() INTERNAL ASSERT FAILED
```
from kernel.