Skip the cases for UT error (#1072)
UT errors:
* test_autograd_xpu.py test_reentrant_parent_error_on_cpu_xpu:
AssertionError: "Simulate error" does not match "grad can be implicitly
created only for scalar outputs".
This error seems to be a random issue. Skip it first, and look forward
to the root cause continuing.
* align the class name skipIfMps to skipIfMPS with main branch.

---------

Signed-off-by: Cheng Penghui <penghui.cheng@intel.com>